services:
  ubuntu_linux:
    container_name: ubuntu-linux
    image: ubuntu:22.04
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ./workspace:/workspace
    command: bash
